# Generated by Django 5.0 on 2023-12-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(default=0),
        ),
    ]
