# Generated by Django 5.0 on 2023-12-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_customuser_age_customuser_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="date_of_birth",
        ),
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(default=15),
        ),
    ]
